require:
  - rubocop-rails
  
AllCops:
  TargetRubyVersion: 3.4.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'vendor/**/*'


Metrics/MethodLength:
  Max: 20